sudo: required
dist: focal
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # download google dsk, install it locally in an instance that is assigned to us by travis CI
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # look at the default install dir of the google cloud sdk, and source the file path bash inc
  # it basically means, there is some config that are going to modify our shell within travis CI inside this file
  # and it's going to apply the config through the source command
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud componenets update kubectl 
  # in order to access gc
  # ask google to activate a service account, and provide the credentials in service-account.json
  # step1: download the service account credential in a json file
  # step2: download and install travis CLI
  # step3: encrypt and upload the json file to travis account
  # step4: in the travis.yml, add code to unencrpt the json file and load it to GC SDK
  - gcloud auth activate-service-account --key-file service-account.json
